# APPLICATION BROWSER
browser=chrome
# APPLICATION URL
url=https://www.demoblaze.com/
# APPLICATION USERNAME AND PASSWORD
username=GayathriEbin
password=gayathriebiN

#credit details
name=Veena
country=India
city=chennai
creditCard=12345678987654
month=may
year=2026
